export function buildBaseTemplate(
  title: string,
  orgName: string,
  dateRange: string,
  generatedBy: string,
  generatedAt: string,
  reportId: string,
  content: string,
  reportType: string,
  tocHtml: string
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; padding: 0; font-family: Arial, sans-serif; font-size: 11pt; color: #0a1628; background: #fff; }
    .watermark { position: fixed; top: 30%; left: 50%; transform: translate(-50%, -50%) rotate(-30deg); font-size: 48pt; color: #e0e0e0; white-space: nowrap; z-index: 0; pointer-events: none; }
    .content { position: relative; z-index: 1; }
    .page-break { page-break-after: always; }
    .no-break { page-break-inside: avoid; }
    header, footer { font-size: 9pt; color: #666; }
    .cover { min-height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 2cm; }
    .cover h1 { font-size: 24pt; margin: 0 0 8px 0; color: #0a1628; }
    .cover .sub { font-size: 12pt; color: #00D4FF; margin-bottom: 24px; }
    .cover .meta { margin-top: 32px; font-size: 10pt; text-align: left; max-width: 400px; }
    .cover .meta p { margin: 4px 0; }
    .cover .footer { margin-top: 48px; font-size: 9pt; color: #666; }
    .toc { padding: 20px 0; }
    .toc h2 { font-size: 14pt; margin-bottom: 12px; color: #00D4FF; }
    .toc ul { list-style: none; padding: 0; margin: 0; }
    .toc li { padding: 4px 0; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border: 1px solid #e0e0e0; padding: 8px 12px; text-align: left; }
    th { background: #0a1628; color: #fff; font-weight: 600; }
    tr:nth-child(even) { background: #f8f8f8; }
    .badge-critical { background: #FF2D2D; color: white; padding: 2px 8px; border-radius: 2px; font-size: 9pt; }
    .badge-danger { background: #FF6B35; color: white; padding: 2px 8px; border-radius: 2px; font-size: 9pt; }
    .badge-warning { background: #FFB700; color: black; padding: 2px 8px; border-radius: 2px; font-size: 9pt; }
    .badge-safe { background: #00C46A; color: white; padding: 2px 8px; border-radius: 2px; font-size: 9pt; }
    .section-title { font-size: 14pt; color: #00D4FF; margin: 24px 0 12px 0; padding-bottom: 4px; border-bottom: 2px solid #00D4FF; }
    .stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }
    .stat-box { border: 1px solid #e0e0e0; padding: 12px; text-align: center; }
    .stat-box .value { font-size: 18pt; font-weight: bold; color: #00D4FF; }
    .stat-box .label { font-size: 9pt; color: #666; }
    @media print {
      .page-break { page-break-after: always; }
      .no-break { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="watermark">ADVANCESAFE — CONFIDENTIAL</div>
  <div class="content">
    <div class="cover page-break">
      <div class="sub">AdvanceSafe</div>
      <h1>SAFETY MANAGEMENT SYSTEM</h1>
      <div style="width: 200px; height: 2px; background: #00D4FF; margin: 16px auto;"></div>
      <h2 style="font-size: 16pt; margin: 24px 0 8px 0;">${escapeHtml(title)}</h2>
      <div class="meta">
        <p><strong>Organization:</strong> ${escapeHtml(orgName)}</p>
        <p><strong>Period:</strong> ${escapeHtml(dateRange)}</p>
        <p><strong>Generated:</strong> ${escapeHtml(generatedAt)}</p>
        <p><strong>Generated By:</strong> ${escapeHtml(generatedBy)}</p>
        <p><strong>Report ID:</strong> ${escapeHtml(reportId)}</p>
      </div>
      <div style="width: 100%; max-width: 300px; height: 1px; background: #e0e0e0; margin: 24px 0;"></div>
      <div class="footer">A Product of Advanced SOS Max<br>Ahmedabad, Gujarat, India</div>
    </div>
    <div class="toc page-break">
      <h2>Table of Contents</h2>
      ${tocHtml}
    </div>
    ${content}
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function badgeClass(status: string): string {
  const s = (status || '').toLowerCase();
  if (s === 'critical') return 'badge-critical';
  if (s === 'danger') return 'badge-danger';
  if (s === 'warning') return 'badge-warning';
  return 'badge-safe';
}

export function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch {
    return iso;
  }
}

export function formatDateTime(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  } catch {
    return iso;
  }
}
